default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: RootAdmin*  
  host: localhost

development:
  <<: *default
  database: food_donation_app_development

test:
  <<: *default
  database: food_donation_app_test

production:
  primary: &primary_production
    <<: *default
    database: food_donation_app_production
    password: <%= ENV['FOOD_DONATION_APP_DATABASE_PASSWORD'] %>